query GetProducts($first: Int, $identifiers: [HasMetafieldsIdentifier!]!, $sortKey: ProductSortKeys, $reverse: Boolean, $query: String) {
    products(sortKey: $sortKey, reverse: $reverse, query: $query, first: $first) {
        edges {
            node {
                id
                handle
                availableForSale
                title
                description
                descriptionHtml
                options {
                    id
                    name
                    values
                }
                priceRange {
                    maxVariantPrice {
                        amount
                        currencyCode
                    }
                    minVariantPrice {
                        amount
                        currencyCode
                    }
                }
                compareAtPriceRange {
                    maxVariantPrice {
                        amount
                        currencyCode
                    }
                    minVariantPrice {
                        amount
                        currencyCode
                    }
                }
                variants(first: 250) {
                    edges {
                        node {
                            id
                            sku
                            barcode
                            title
                            availableForSale
                            selectedOptions {
                                name
                                value
                            }
                            price {
                                amount
                                currencyCode
                            }
                            image {
                                url
                                altText
                                width
                                height
                            }
                            quantityAvailable
                            quantityRule {
                                increment
                                minimum
                                maximum
                            }
                            taxable
                            compareAtPrice {
                                amount
                                currencyCode
                            }
                        }
                    }
                }
                featuredImage {
                    url
                    altText
                    width
                    height
                }
                images(first: 20) {
                    edges {
                        node {
                            url
                            altText
                            width
                            height
                        }
                    }
                }
                metafields(identifiers: $identifiers) {
                    id
                    type
                    key
                    value
                    references(first: 250) {
                        nodes {
                            ... on Metaobject {
                                id
                                handle
                                type
                                fields {
                                    key
                                    value
                                }
                            }
                        }
                    }
                }
                seo {
                    description
                    title
                }
                tags
                updatedAt
            }
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}